# Change to your website's URL (NO trailing slash)
#For local dev, change to: http://localhost:1313
baseURL = "https://name.gitlab.io/documentation/"
#baseURL = "/"
#relativeURLs = true


# Change to your Brand or Website Title
title = "Documentation"

author = "test"

# Language codes (lowercase)
languageCode = "en-us"
defaultContentLanguage = "en"

# Which theme to use
theme = "axiom"

# Pagination (increase number for production)
paginate = 2

# Canonify relative URLs using baseURL
canonifyURLs = false
